//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expressium.CodeGenerators.Java.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expressium.CodeGenerators.Java.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.Logger;
        ///import org.testng.Assert;
        ///
        ///public class Asserts {
        ///    protected Logger logger;
        ///    
        ///    public Asserts(Logger logger) {
        ///        this.logger = logger;
        ///    }
        ///
        ///    public void assertEquals(String expected, String actual, String message) {
        ///        try {
        ///            Assert.assertEquals(expected, actual, message);
        ///
        ///            logger.info(String.format(&quot;%s&quot;, message));
        ///            logger.info(String.format(&quot;Expected to be [%s] and was [%s] - PASSED&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Asserts {
            get {
                return ResourceManager.GetString("Asserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import Controls.*;
        ///import org.apache.log4j.Logger;
        ///import org.openqa.selenium.*;
        ///import org.openqa.selenium.support.PageFactory;
        ///import org.openqa.selenium.support.pagefactory.AjaxElementLocatorFactory;
        ///import org.openqa.selenium.support.ui.ExpectedCondition;
        ///import org.openqa.selenium.support.ui.ExpectedConditions;
        ///import org.openqa.selenium.support.ui.WebDriverWait;
        ///
        ///import java.time.Duration;
        ///import java.util.ArrayList;
        ///
        ///public class BasePage {
        ///    protected Logger logger;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePageByControls {
            get {
                return ResourceManager.GetString("BasePageByControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.Logger;
        ///import org.openqa.selenium.*;
        ///import org.openqa.selenium.support.PageFactory;
        ///import org.openqa.selenium.support.pagefactory.AjaxElementLocatorFactory;
        ///import org.openqa.selenium.support.ui.ExpectedCondition;
        ///import org.openqa.selenium.support.ui.ExpectedConditions;
        ///import org.openqa.selenium.support.ui.WebDriverWait;
        ///
        ///import java.time.Duration;
        ///import java.util.ArrayList;
        ///
        ///public class BasePage {
        ///    protected Logger logger;
        ///    protected WebDr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePageByLocators {
            get {
                return ResourceManager.GetString("BasePageByLocators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.Logger;
        ///import org.openqa.selenium.*;
        ///import org.openqa.selenium.support.PageFactory;
        ///import org.openqa.selenium.support.pagefactory.AjaxElementLocatorFactory;
        ///import org.openqa.selenium.support.ui.ExpectedCondition;
        ///import org.openqa.selenium.support.ui.ExpectedConditions;
        ///import org.openqa.selenium.support.ui.WebDriverWait;
        ///
        ///import java.time.Duration;
        ///import java.util.ArrayList;
        ///
        ///public class BasePage {
        ///    protected Logger logger;
        ///    protected WebDr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePagePageFactory {
            get {
                return ResourceManager.GetString("BasePagePageFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package BusinessTests.Steps;
        ///
        ///import Bases.Asserts;
        ///import org.openqa.selenium.WebDriver;
        ///import org.apache.log4j.Logger;
        ///
        ///public class BaseSteps {
        ///    protected static Logger logger;
        ///    protected static WebDriver driver;
        ///    protected static Asserts asserts;
        ///
        ///    public static void initialize(Logger logger, WebDriver driver, Asserts asserts) {
        ///        BaseSteps.logger = logger;
        ///        BaseSteps.driver = driver;
        ///        BaseSteps.asserts = asserts;
        ///    }
        ///}.
        /// </summary>
        internal static string BaseSteps {
            get {
                return ResourceManager.GetString("BaseSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.Logger;
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///import org.openqa.selenium.WebElement;
        ///
        ///import java.util.List;
        ///
        ///public class BaseTable extends BasePage {
        ///    protected By baseLocator;
        ///
        ///    public BaseTable(Logger logger, WebDriver driver, By baseLocator) throws Exception {
        ///        super(logger, driver);
        ///
        ///        this.baseLocator = baseLocator;
        ///    }
        ///
        ///    public int getNumberOfRows() {
        ///        logger.info(&quot;getNumberOfRows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTable {
            get {
                return ResourceManager.GetString("BaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.Logger;
        ///import Controls.WebTable;
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class BaseTable extends BasePage {
        ///    protected WebTable baseControl;
        ///
        ///    public BaseTable(Logger logger, WebDriver driver, By baseLocator) throws Exception {
        ///        super(logger, driver);
        ///
        ///        baseControl = new WebTable(driver, baseLocator);
        ///    }
        ///
        ///    public int getNumberOfRows() {
        ///        logger.info(&quot;getNumberOfRows()&quot;);
        ///        r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTableByControls {
            get {
                return ResourceManager.GetString("BaseTableByControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///public class BaseTest extends BaseTestFixture {
        ///    public enum EnvironmentTypes {
        ///        DEV,
        ///        TEST,
        ///        PROD
        ///    }
        ///
        ///    public BaseTest() {
        ///        company = &quot;$Company$&quot;;
        ///        project = &quot;$Project$&quot;;
        ///        environmentId = EnvironmentTypes.TEST.toString();
        ///        url = &quot;$Url$&quot;;
        ///        logging = true;
        ///        loggingPath = &quot;C:\\Temp\\$Company$\\$Project$\\TestResults&quot;;
        ///        browser = &quot;$BrowserType$&quot;;
        ///        maximize = true;
        ///        headless = false;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTest {
            get {
                return ResourceManager.GetString("BaseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.commons.io.FileUtils;
        ///import org.apache.log4j.Logger;
        ///import org.openqa.selenium.JavascriptExecutor;
        ///import org.openqa.selenium.OutputType;
        ///import org.openqa.selenium.TakesScreenshot;
        ///import org.openqa.selenium.WebDriver;
        ///import org.testng.ITestContext;
        ///import org.testng.ITestNGMethod;
        ///import org.testng.annotations.AfterClass;
        ///import org.testng.annotations.BeforeClass;
        ///
        ///import java.io.File;
        ///import java.time.LocalDateTime;
        ///import java.time.format.DateTimeForma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTestFixture {
            get {
                return ResourceManager.GetString("BaseTestFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package BusinessTests.Steps;
        ///
        ///import Bases.Asserts;
        ///import Bases.BaseTest;
        ///import Bases.LoggerInitializer;
        ///import io.cucumber.core.backend.TestCaseState;
        ///import io.cucumber.java.After;
        ///import io.cucumber.java.Before;
        ///import io.cucumber.java.Scenario;
        ///import org.apache.commons.lang3.reflect.FieldUtils;
        ///import org.apache.commons.lang3.reflect.MethodUtils;
        ///
        ///import java.io.File;
        ///import java.lang.reflect.Field;
        ///import java.lang.reflect.Method;
        ///import java.time.LocalDateTime;
        ///import java.time.form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTestFixtureBDD {
            get {
                return ResourceManager.GetString("BaseTestFixtureBDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE suite SYSTEM &quot;http://testng.org/testng-1.0.dtd&quot;&gt;
        ///&lt;suite name=&quot;BusinessTests&quot; configfailurepolicy=&quot;continue&quot;&gt;
        ///    &lt;test name=&quot;BusinessTests&quot;&gt;
        ///        &lt;classes&gt;
        ///            &lt;class name=&quot;BusinessTests.TestRunners.BusinessTests&quot;&gt;&lt;/class&gt;
        ///        &lt;/classes&gt;
        ///    &lt;/test&gt;
        ///&lt;/suite&gt;.
        /// </summary>
        internal static string BddTests {
            get {
                return ResourceManager.GetString("BddTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///public class Configuration {
        ///
        ///    public enum Profiles {
        ///        Development,
        ///        Test,
        ///        PreProduction,
        ///        Production
        ///    }
        ///
        ///    private String company;
        ///    private String project;
        ///    private String environment;
        ///    private String url;
        ///    private String username;
        ///    private String password;
        ///    private boolean logging;
        ///    private String loggingPath;
        ///    private String browserType;
        ///    private boolean maximize;
        ///    private boolean headless;
        ///    privat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature: Login
        ///	As a User
        ///	I want to login on the web application
        ///	So that I can administrate my product orders
        ///
        ///@BusinessTests @Id:TC200??
        ///Scenario: Successful User Login with Valid Credentials
        ///	Given I am logged in with valid user credentials
        ///	Then I should be redirected to the Home page.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.*;
        ///
        ///public class LoggerInitializer {
        ///    public static Logger initialize(String name, String filePath) {
        ///        Logger logger = Logger.getLogger(name);
        ///
        ///        PatternLayout patternLayout = new PatternLayout();
        ///        patternLayout.setConversionPattern(&quot;%d{HH:mm:ss} %p %C # %m%n&quot;);
        ///        patternLayout.activateOptions();
        ///
        ///        ConsoleAppender consoleAppender = new ConsoleAppender();
        ///        consoleAppender.setLayout(patternLayout);
        ///        console [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logger {
            get {
                return ResourceManager.GetString("Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package BusinessTests.Steps;
        ///
        ///import io.cucumber.java.en.Given;
        ///import io.cucumber.java.en.Then;
        ///import io.cucumber.java.en.When;
        ///import Bases.Asserts;
        ///
        ///public class LoginSteps extends BaseSteps {
        ///
        ///    @Given(&quot;I am logged in with valid user credentials&quot;)
        ///    public void i_am_logged_in_with_valid_user_credentials() throws Exception {
        ///       throw new io.cucumber.java.PendingException();
        ///    }
        ///    @Then(&quot;I should be redirected to the Home page&quot;)
        ///    public void i_should_be_redirected_to_the_home [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoginSteps {
            get {
                return ResourceManager.GetString("LoginSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;project xmlns=&quot;http://maven.apache.org/POM/4.0.0&quot;
        ///         xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xsi:schemaLocation=&quot;http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd&quot;&gt;
        ///	&lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
        ///
        ///    &lt;groupId&gt;dk.expressium.java&lt;/groupId&gt;
        ///	&lt;artifactId&gt;ExpressiumCoffeeshopTests&lt;/artifactId&gt;
        ///	&lt;version&gt;1.0-SNAPSHOT&lt;/version&gt;
        ///
        ///	&lt;build&gt;
        ///		&lt;plugins&gt;
        ///			&lt;plugin&gt;
        ///				&lt;groupId&gt;org.apache.maven.plugins&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pom {
            get {
                return ResourceManager.GetString("Pom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import java.security.SecureRandom;
        ///import java.text.SimpleDateFormat;
        ///import java.util.Date;
        ///import java.util.Random;
        ///import java.util.stream.Collectors;
        ///
        ///public class Randomizer {
        ///    private static final Random random = new SecureRandom();
        ///
        ///    public static String getRandomString(int length) {
        ///        final String chars = &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789&quot;;
        ///        return random.ints(length, 0, chars.length())
        ///                .mapToObj(chars::ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Randomizer {
            get {
                return ResourceManager.GetString("Randomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE suite SYSTEM &quot;http://testng.org/testng-1.0.dtd&quot;&gt;
        ///&lt;suite name=&quot;RegressionTests&quot; configfailurepolicy=&quot;continue&quot;&gt;
        ///    &lt;suite-files&gt;
        ///        &lt;suite-file path=&quot;UITests.xml&quot;/&gt;
        ///        &lt;suite-file path=&quot;BusinessTests.xml&quot;/&gt;
        ///    &lt;/suite-files&gt;
        ///&lt;/suite&gt;.
        /// </summary>
        internal static string RegressionTests {
            get {
                return ResourceManager.GetString("RegressionTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import java.awt.AWTException;
        ///import java.awt.Dimension;
        ///import java.awt.GraphicsConfiguration;
        ///import java.awt.GraphicsEnvironment;
        ///import java.awt.Rectangle;
        ///import java.awt.Toolkit;
        ///import java.io.File;
        ///import java.io.IOException;
        ///
        ///import org.monte.media.Format;
        ///import org.monte.media.FormatKeys.MediaType;
        ///import org.monte.media.Registry;
        ///import org.monte.media.math.Rational;
        ///import org.monte.screenrecorder.ScreenRecorder;
        ///
        ///import static org.monte.media.AudioFormatKeys.*; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScreenRecorderUtility {
            get {
                return ResourceManager.GetString("ScreenRecorderUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package BusinessTests.TestRunners;
        ///
        ///import io.cucumber.testng.AbstractTestNGCucumberTests;
        ///import io.cucumber.testng.CucumberOptions;
        ///import org.testng.annotations.DataProvider;
        ///
        ///@CucumberOptions(
        ///        features = {&quot;src/test/java/BusinessTests/Features&quot;},
        ///        glue = {&quot;BusinessTests/Steps&quot;},
        ///        tags = &quot;@BusinessTests&quot;
        ///)
        ///public class BusinessTests extends AbstractTestNGCucumberTests {
        ///
        ///    @Override
        ///    @DataProvider(parallel = false)
        ///    public Object[][] scenarios() {
        ///        retu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRunner {
            get {
                return ResourceManager.GetString("TestRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE suite SYSTEM &quot;http://testng.org/testng-1.0.dtd&quot;&gt;
        ///&lt;suite name=&quot;UiTests&quot; configfailurepolicy=&quot;continue&quot;&gt;
        ///    &lt;test name=&quot;UITests&quot;&gt;
        ///        &lt;packages&gt;
        ///            &lt;package name=&quot;UITests&quot; /&gt;
        ///        &lt;/packages&gt;
        ///    &lt;/test&gt;
        ///&lt;/suite&gt;.
        /// </summary>
        internal static string TestRunnerUITests {
            get {
                return ResourceManager.GetString("TestRunnerUITests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebButton extends WebControl {
        ///
        ///    public WebButton(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebButton(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public void click() {
        ///        waitForElementIsEnabled();
        ///        highlightElementAsAction();
        ///        highlightElementClear();
        ///        clickE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebButton {
            get {
                return ResourceManager.GetString("WebButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebCheckBox extends WebControl {
        ///
        ///    public WebCheckBox(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebCheckBox(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public void setChecked(boolean value) {
        ///        waitForElementIsEnabled();
        ///        if ((!isSelected() &amp;&amp; value) || (isSelected() &amp;&amp; !val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebCheckBox {
            get {
                return ResourceManager.GetString("WebCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import Bases.WebElements;
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///import org.openqa.selenium.WebElement;
        ///import org.openqa.selenium.support.ui.Select;
        ///
        ///public class WebComboBox extends WebControl {
        ///
        ///    public WebComboBox(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebComboBox(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public void selectByText [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebComboBox {
            get {
                return ResourceManager.GetString("WebComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import Bases.WebElements;
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///import org.openqa.selenium.WebElement;
        ///
        ///public class WebControl {
        ///    protected WebDriver driver;
        ///    protected By locator;
        ///    protected By childLocator;
        ///    protected WebElement element;
        ///    protected boolean cached = false;
        ///
        ///    public WebControl(WebDriver driver, By locator) {
        ///        this.driver = driver;
        ///        this.locator = locator;
        ///    }
        ///
        ///    public WebControl(WebDri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebControl {
            get {
                return ResourceManager.GetString("WebControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.openqa.selenium.WebDriver;
        ///import org.openqa.selenium.chrome.ChromeDriver;
        ///import org.openqa.selenium.chrome.ChromeOptions;
        ///import org.openqa.selenium.edge.EdgeDriver;
        ///import org.openqa.selenium.edge.EdgeOptions;
        ///import org.openqa.selenium.firefox.FirefoxDriver;
        ///import org.openqa.selenium.firefox.FirefoxOptions;
        ///import org.openqa.selenium.firefox.FirefoxProfile;
        ///
        ///public class WebDriverFactory {
        ///    public enum BrowserTypes {
        ///        Chrome,
        ///        Edge,
        ///        Fir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebDriverFactory {
            get {
                return ResourceManager.GetString("WebDriverFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Bases;
        ///
        ///import org.apache.log4j.Logger;
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.JavascriptExecutor;
        ///import org.openqa.selenium.WebDriver;
        ///import org.openqa.selenium.WebElement;
        ///import org.openqa.selenium.interactions.Actions;
        ///import org.openqa.selenium.support.ui.ExpectedConditions;
        ///import org.openqa.selenium.support.ui.Select;
        ///import org.openqa.selenium.support.ui.WebDriverWait;
        ///
        ///import java.time.Duration;
        ///import java.util.List;
        ///
        ///public class WebElements {
        ///    priv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebElements {
            get {
                return ResourceManager.GetString("WebElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebLink extends WebButton {
        ///
        ///    public WebLink(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebLink(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///}.
        /// </summary>
        internal static string WebLink {
            get {
                return ResourceManager.GetString("WebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebListBox extends WebComboBox {
        ///
        ///    public WebListBox(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebListBox(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///}.
        /// </summary>
        internal static string WebListBox {
            get {
                return ResourceManager.GetString("WebListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebRadioButton extends WebControl {
        ///
        ///    public WebRadioButton(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebRadioButton(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public void setSelected(boolean value) {
        ///        waitForElementIsEnabled();
        ///        if (!isSelected() &amp;&amp; value) {
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebRadioButton {
            get {
                return ResourceManager.GetString("WebRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///import org.openqa.selenium.WebElement;
        ///
        ///import java.util.List;
        ///
        ///public class WebTable extends WebControl {
        ///
        ///    public WebTable(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebTable(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public int getNumberOfRows() {
        ///        return getElement().findElements(By.xpath [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebTable {
            get {
                return ResourceManager.GetString("WebTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebText extends WebControl {
        ///
        ///    public WebText(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebText(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public String getText() {
        ///        waitForElementIsVisible();
        ///        highlightElementAsValidation();
        ///        return getElementText();
        ///    }
        ///
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebText {
            get {
                return ResourceManager.GetString("WebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package Controls;
        ///
        ///import org.openqa.selenium.By;
        ///import org.openqa.selenium.WebDriver;
        ///
        ///public class WebTextBox extends WebControl {
        ///
        ///    public WebTextBox(WebDriver driver, By locator) {
        ///        super(driver, locator);
        ///    }
        ///
        ///    public WebTextBox(WebDriver driver, By locator, By childLocator) {
        ///        super(driver, locator, childLocator);
        ///    }
        ///
        ///    public void setText(String value) {
        ///        if (value == null) {
        ///            return;
        ///        }
        ///
        ///        waitForElementIsEnabled();
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebTextBox {
            get {
                return ResourceManager.GetString("WebTextBox", resourceCulture);
            }
        }
    }
}
