//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expressium.CodeGenerators.Java.Selenium.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expressium.CodeGenerators.Java.Selenium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asserts.
        /// </summary>
        internal static string Asserts {
            get {
                return ResourceManager.GetString("Asserts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BasePage.
        /// </summary>
        internal static string BasePage {
            get {
                return ResourceManager.GetString("BasePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BaseTable.
        /// </summary>
        internal static string BaseTable {
            get {
                return ResourceManager.GetString("BaseTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BaseTest.
        /// </summary>
        internal static string BaseTest {
            get {
                return ResourceManager.GetString("BaseTest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BaseTestFixture.
        /// </summary>
        internal static string BaseTestFixture {
            get {
                return ResourceManager.GetString("BaseTestFixture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrowserFactory.
        /// </summary>
        internal static string BrowserFactory {
            get {
                return ResourceManager.GetString("BrowserFactory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrowserManager.
        /// </summary>
        internal static string BrowserManager {
            get {
                return ResourceManager.GetString("BrowserManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ConfigurationJson.
        /// </summary>
        internal static string ConfigurationJson {
            get {
                return ResourceManager.GetString("ConfigurationJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitIgnore.
        /// </summary>
        internal static string GitIgnore {
            get {
                return ResourceManager.GetString("GitIgnore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        internal static string Logger {
            get {
                return ResourceManager.GetString("Logger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PomXml.
        /// </summary>
        internal static string PomXml {
            get {
                return ResourceManager.GetString("PomXml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Randomizer.
        /// </summary>
        internal static string Randomizer {
            get {
                return ResourceManager.GetString("Randomizer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebButton.
        /// </summary>
        internal static string WebButton {
            get {
                return ResourceManager.GetString("WebButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebCheckBox.
        /// </summary>
        internal static string WebCheckBox {
            get {
                return ResourceManager.GetString("WebCheckBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebComboBox.
        /// </summary>
        internal static string WebComboBox {
            get {
                return ResourceManager.GetString("WebComboBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebControl.
        /// </summary>
        internal static string WebControl {
            get {
                return ResourceManager.GetString("WebControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebLink.
        /// </summary>
        internal static string WebLink {
            get {
                return ResourceManager.GetString("WebLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebListBox.
        /// </summary>
        internal static string WebListBox {
            get {
                return ResourceManager.GetString("WebListBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebRadioButton.
        /// </summary>
        internal static string WebRadioButton {
            get {
                return ResourceManager.GetString("WebRadioButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebTable.
        /// </summary>
        internal static string WebTable {
            get {
                return ResourceManager.GetString("WebTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebText.
        /// </summary>
        internal static string WebText {
            get {
                return ResourceManager.GetString("WebText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebTextBox.
        /// </summary>
        internal static string WebTextBox {
            get {
                return ResourceManager.GetString("WebTextBox", resourceCulture);
            }
        }
    }
}
